### ISSUE TITLE
Make the page title reflect the title of the currently opened video.

### ISSUE THREAD

**Issue by elkorn** [kennethlynne/ndcvideos.com#201]
I'm using a Chrome extension for adding tasks based on the current page to Asana.
The default title for a task is its pages' `title` attribute.
It would be very useful if the video details route put `{{currentVideoTitle}} | NDCVideos.com | Norwegian Developers...` in the page title.

**Comment by sarabander** [comment]
I second that request. It would make bookmarking quicker.
