### ISSUE TITLE
Please consider making the video title a hyperlink aka <a> tag

### ISSUE THREAD

**Issue by randyburden** [kennethlynne/ndcvideos.com#203]
I wanted to queue up multiple videos to watch by opening the videos in different tabs but currently there is no hyperlink. Currently when you hover your mouse over each video, the cursor changes to a pointer aka hand which leads the user to believe that the entire video or text is a hyperlink which can be copied and/or opened in a new tab but this is not the case and is very disconcerting.

I would propose at least making each video title an actual hyperlink to support the ability to copy the video url and/or open the video in a new tab. I modified the HTML in Google Chrome's Developer Tools wrapping the title in an <a> tag and the result provided the expected behavior and also resulted in a very visually appealing result where the hyperlink becomes underlined when hovered over providing nice feedback to the user that the title is a hyperlink.

```js
<h3><a href="#/app/video/3391">Workshop: Lean Presentation Skills™ Part 2 by Jessica Shternshus</a></h3>
```

From looking at the code, it seems you would just have to add the hyperlink to this line in this file: https://github.com/kennethlynne/ndcvideos.com/blob/master/app/components/video-list-item/video-list-item.html#L11

**Comment by sarabander** [comment]
I support this proposition.

**Comment by sarabander** [comment]
Splendid, thanks! (For both #201 and this one.)
